services:
  postgres:
    image: postgres:latest
    container_name: postgres
    healthcheck:
      test: ["CMD-SHELL", "psql -U ${POSTGRES_USER} --list"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend-network

  redis:
    image: redis:latest
    container_name: redis
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=aosjdblas123
    command: redis-server --requirepass $REDIS_PASSWORD
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend-network

  bot:
    container_name: bot
    hostname: bot
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    image: bot:latest
    networks:
      - backend-network

volumes:
  postgres-data:
  pgadmin-data:

networks:
  backend-network:
    driver: bridge
    name: backend-network
    driver_opts:
      com.docker.network.driver.mtu: 1450
